
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Outfit } from "next/font/google";
import Header from "./component/Header";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import ParentFolderState from "./context/ParentFolderContext";





const font = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

 
  
  return (
    
    <ClerkProvider>
     


      <html lang="en">
        <body className={font.className}>
          <ParentFolderState>

          <Header/>
          <main >
            <div className="flex flex-col items-start justify-center  ">
          {children}
              
            </div>
          </main>
<ToastContainer/>
          </ParentFolderState>
        </body>
      </html>

     
    </ClerkProvider>
  );
}
